# -*- coding: utf-8 -*-
"""Financial Inclusion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gJIS2G70eKjozOPtRELz6-YnZjoqTGkA
"""

import os

print(os.listdir())

import pandas as pd

train = pd.read_csv("Train.csv")

train.head()

train.info()

train.shape

train['bank_account'].value_counts()

train.groupby('education_level')['bank_account'].value_counts()

train.groupby('cellphone_access')['bank_account'].value_counts()

from sklearn.preprocessing import LabelEncoder

df = train.copy()

le = LabelEncoder()

for col in df.columns:
    if df[col].dtype == 'object':
        df[col] = le.fit_transform(df[col])

df.head()

X = df.drop('bank_account', axis=1)
y = df['bank_account']

print(X.shape)
print(y.shape)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print(X_train.shape)
print(X_test.shape)

from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

model.fit(X_train, y_train)

predictions = model.predict(X_test)

predictions[:10]

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, predictions)

print("Accuracy:", accuracy)

from sklearn.metrics import classification_report

print(classification_report(y_test, predictions))

import pandas as pd

feature_importance = pd.DataFrame({
    'Feature': X.columns,
    'Importance': model.feature_importances_
})

feature_importance.sort_values(
    by='Importance',
    ascending=False
).head(10)

test = pd.read_csv('Test.csv')

print(test.shape)
test.head()

print(test.columns)

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for col in df.columns:
    if df[col].dtype == 'object':
        df[col] = le.fit_transform(df[col])

X.head()

from sklearn.preprocessing import LabelEncoder

test_processed = test.copy()

for col in test_processed.columns:
    if test_processed[col].dtype == 'object':
        le = LabelEncoder()
        test_processed[col] = le.fit_transform(test_processed[col])

test_processed.head()

print(test_processed.shape)

predictions = model.predict(test_processed)

print(predictions[:10])

submission = pd.DataFrame({
    'unique_id': test['uniqueid'] + ' x ' + test['country'],
    'bank_account': predictions
})

submission.head()

submission.to_csv('submission.csv', index=False)

from google.colab import files

files.download('submission.csv')

submission.head()

print(submission.head())
print(submission.columns)
print(submission.shape)
print(submission.isnull().sum())

sample_submission.head()
sample_submission.columns

sample_submission.head()
sample_submission.columns

print(sample_submission.head())
print(sample_submission.columns)
print(sample_submission.shape)

sample_submission = pd.read_csv("sample_submission.csv")

predictions = model.predict(test_processed)

test.head()

test.info()

sample = pd.read_csv('SampleSubmission.csv')
sample.head()